<?php

// call the page header
$page_title = "About Us";
include_once 'includes/header.php';
?>

<div class="body">
<p>
    Sharina is self help group created to help people borrow loans and contribute money in the organisation.<br/>
    Membership is by registration whereby members give out their details. This organisation is to increase productivity 
    in the economy for its members.
</p>
    <p>
        By signing up, you will automatically be deducted a non-refundable KSHs 200 for registration.
    </p>
    <p>
        Sharina&trade; has several modules for fully operations. These are documented below:<br/>
        <ol class="list-styled col-lg-offset-1">
        <li><a href="about-us.php/#registrationform">Registration Form</a></li>
        <li><a href="about-us.php/#loginform">Login Form</a></li>
        <li><a href="about-us.php/#contributionform">Contribution Form</a></li>
        <li><a href="about-us.php/#lendingform">Lending Form</a></li>
        <span class="bold">Receipts</span>
        <li><a href="about-us.php/#registrationreceipt">Registration Receipt</a></li>
        <li><a href="about-us.php/#contributionreceipt">Contribution Receipt</a></li>
        <li><a href="about-us.php/#lendingreceipt">Lending Receipt</a></li>
        <li><a href="about-us.php/#yearlycontributions">Yearly Contributions</a></li>
        <li><a href="about-us.php/#loanstatement">Loan Statement</a></li>
        <li><a href="about-us.php/#membercontributionstatement">Member Contribution Statement</a></li>
        </ol>
    </p>

    <div id="registrationform">
        <div class="media-heading" style="font-weight: bolder;font-size: larger;text-decoration: underline">Registration Form</div>
        <p>
            The registration form is used to create an account with <?php echo PROJECT_NAME; ?>. This form requires you to input
            several of your personal details to identify you on our site. We promise to keep all data provided to us confidential
            as outlined in our <a href="/">Privacy Policy</a>. These details include:
            <ul>
            <li>Your First Name</li>
            <li>Your last Name</li>
            <li>A Username To be used on <?php echo PROJECT_NAME; ?></li>
            <li>A valid email address that you have access to</li>
            <li>A valid phone number that you have access to</li>
            <li>An optional password (password guildelines are outlined in <a href="/">Privacy Policy#passwords</a> </li>
        </ul>
        </p>
    </div>

    <div id="loginform">
        <div class="media-heading" style="font-weight: bolder;font-size: larger;text-decoration: underline">Login Form</div>
        <p>
            After a succesful registration, a user can then log on to our site. To be able to log in, you have to pass
            two criteria:
            <ol>
                <li>Have successfully registered with us</li>
                <li>Have access to our login page</li>
            </ol>
        Due to privacy and security concerns, some page's content cannot be fully or partially viewed unless you have logged
        in to <?php echo PROJECT_NAME; ?>. These pages will have accompanying messages informing you on what to do in case of
        this, which is usually to login.<br/>
        To log in to <?php echo PROJECT_NAME;?>, you will need either the username you registered with or the email address
        combined with the correct pasword you also registered with. Without these, you will be locked ot and you will need to
        contact us for your account re-activation.
        </p>
    </div>

    <div id="contributionform">
        <div class="media-heading" style="font-weight: bolder;font-size: larger;text-decoration: underline">Contribution Form</div>
        <p>
            The contributions form is a form that enables users to make contributions in their usual way.<br/>
            If you are required to make a contribution every week, then you can use this form to do that. Most of this form
            cannot be edited by hte uer except the <b>amount</b> section. All other values are generated by the system automatically.
            <br/>
            A user can make seeral subsequent contributions to add up up to whatever amount they desire.
            These can then be deducted whenever they hold a meeting and the balance will still reflect. <br/>
            A user can view their contributions summary through the <a href="includes/#"><b>Contribution Summary</b></a> page.
        </p>
    </div>

    <div id="lendingform">
        <div class="media-heading" style="font-weight: bolder;font-size: larger;text-decoration: underline">Lending Form</div>
        <p>
            The lending form allows a user to request for a loan from <?php echo PROJECT_NAME; ?>. <br/>
            When requesting a loan, we require several details from you. These are:
            <ol>
            <li>Your member number</li>
            <li>The loan receipt number</li>
            <li>The amount you wish to be loaned</li>
            <li>The duration you will take to repay the loan</li>
            <li>A brief explanation why you should be loaned the money</li>
            <li>The amount you can pay as monthly installments</li>
        </ol>
        Numbers <b>1</b> and <b>2</b> above are generated automatically from the details of your registration.
        However, the rest you will need to fill out.<br/>
        There are also a number of factors that are constant with us; for instance, our interest rate ia a constant <b><i><u>4% per month</u></i></b>.
        The system will calculate these, together with the amount to be paid.<br/>
        <pre>
            <b>Note that</b> the monthly installment should not be less that 6.2% of the total loan requested.
        </pre>
        </p>
    </div>
</div>

<?php
include_once "includes/footer.php";
?>
